CREATE TABLE TEMPERATURES (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  temperature_value DOUBLE NOT NULL,
  date_time TIMESTAMP NOT NULL
);

INSERT INTO TEMPERATURES (temperature_value, date_time)
VALUES (20.0, '2025-08-10T18:36:00');